services:
    app:
        container_name: fe.shoes
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        volumes:
            - './:/app:delegated'
        ports:
            - '8080:8080'
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
