services:
    vue-app:
        build:
            context: ./
            dockerfile: docker/app.dockerfile
        container_name: fe.shoes
        restart: always
        ports:
            - "8080:8080"
        networks:
            - laravel
networks:
  laravel:
    driver: bridge